### ISSUE TITLE
User manual document

### ISSUE THREAD

**Issue by HeisenbergJoker** [wuhuagumu/electronic-susceptibility#1]
Hello, is there any documentation for your python script that uses Wannier90 and vasp as an interface to calculate the electronic magnetic susceptibility? Many thanks！

**Comment by liu-xy** [comment]
Sorry I don't have documentation. The main idea is to use Wannier90 to interpolate the Fermi surface and calculate its real and imaginary susceptibilities. It should be quite straight forward.

**Comment by wuhuagumu** [comment]
Sorry I don't have document. The main idea is to use Wannier90 to interpolate Fermi surface. The real and imaginary susceptibilities are calculated from the interpolated Fermi surface. It is quite straight forward and relatively self-evident though.
